### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Klaider** [Manishearth/rust-gc#131]
@Manishearth Can you publish the current version of `gc`? I'm planning on using the `CoerceUnsized` implementation.

**Comment by Manishearth** [comment]
Any reason for closing this? I'm happy to cut a release soon (An easy way to make me do a release is to just make a PR that bumps versions in Cargo.toml)

**Comment by Klaider** [comment]
Thanks, I did not think I could PR.
