### ISSUE TITLE
[Question] How to support tag pointers for interpreter implementation

### ISSUE THREAD

**Issue by higepon** [Manishearth/rust-gc#150]
Hi there,
I'm wondering how we can support tagged pointers in Rust GC. Is there any interpreter implementation which is using tag bits for their object system + Rust GC?

## What I mean by tagged pointers
![raw_pointer](https://user-images.githubusercontent.com/54491/205279138-4520b936-9f5c-4fbd-996a-20bc9b148b46.png)

## What I did
I've read [Writing Interpreters in Rust: a Guide](https://rust-hosted-langs.github.io/book/introduction.html) and [A Tour of Safe Tracing GC Designs in Rust - In Pursuit of Laziness](https://manishearth.github.io/blog/2021/04/05/a-tour-of-safe-tracing-gc-designs-in-rust/) and summarized my understanding in my blog [Trace - Understanding Rust GC](https://higepon.hatenablog.com/entry/2022/12/01/090823) and [Finalize, Sweep and Rooting - Understanding Rust GC](https://higepon.hatenablog.com/entry/2022/12/02/045445). So I think I understand how it work as a big picture. But I'm not very sure if my requirements are easy to implement or not suitable for Rust GC.

### Trace
Let's say a `GC`-ed struct has `Object` as its field. I think we can trace a raw pointer to Pair struct in the field by checking least significant bits of raw_val of the `Object`. I don't know how to implement it in Rust GC but it seems doable.

### Rooting
I have no idea how we root or unroot. Because type of raw_val is not GC<T> but isize, I don't think the GC can track root/unroot properly.

## Background
We have  [Scheme interpreter](https://github.com/higepon/mosh) which conforms to the latest specification of Scheme language. It's written in C++ with Boehm GC. And I'm exploring if we can rewrite it in Rust. I already wrote [a tiny tiny playground](https://github.com/higepon/mosh/blob/rust_test/rmosh/src/main.rs) in Rust but the most unknown there is GC integration. I would really appreciate your insights and thoughts here.

thank you in advance,
Taro

**Comment by Manishearth** [comment]
The GC pointer already uses tag bits to store rootedness. I don't think anyone is doing custom tag bits with rust-gc.

> I have no idea how we root or unroot. Because type of raw_val is not GC but isize, I don't think the GC can track root/unroot properly.



Custom Trace impls.

**Comment by higepon** [comment]
Thank you for your answer. Much appreciated. Have a nice weekend!
