### ISSUE TITLE
Implement Trace/Finalize for PhantomData?

### ISSUE THREAD

**Issue by helixbass** [Manishearth/rust-gc#152]
Hi, I'm working on wiring up this crate in a project and ran into trying to derive `Trace`/`Finalize` for a struct containing a `PhantomData`, if I understand correctly then (because `PhantomData` doesn't actually contain anything to trace or finalize at runtime) this crate should be able to include pre-packaged implementations of `Trace`/`Finalize` for `PhantomData<T>`?

**Comment by Manishearth** [comment]
I'd accept a PR doing this

**Comment by helixbass** [comment]
Hmm actually there appear to already be such derive's present for `PhantomData` ([here](https://github.com/Manishearth/rust-gc/blob/master/gc/src/trace.rs#L356)). But I don't see it show up in the list of "Implementations on Foreign Types" on the [docs.rs docs for `Trace`](https://docs.rs/gc/latest/gc/trait.Trace.html), and it didn't appear to be "kicking in" locally during compilation - so maybe there is something "magic" about `PhantomData` that has been making these derive's silently "fail" (in the sense of not being visible to the compiler, I guess) for some time?

**Comment by andersk** [comment]
This was fixed in Git by #61, but that’s not in a release yet. (I did note on that PR that one of the other instances it added is wrong.)

**Comment by helixbass** [comment]
Ah ok I got thrown off by it saying "5 years ago" for the `PhantomData`-related lines of code when looking at Github blame view (not seeing that the PR was merged more recently than that)

I can work around this one easily (just manually adding `#[unsafe_ignore_trace]` on `PhantomData` fields) but I'm also now using the `serde` `Serialize` implementation that also appears to not have been included in a release yet so would +1 doing a release soon-ish so that I don't have to use a git dependency for this crate indefinitely, thanks

**Comment by Manishearth** [comment]
I don't have time to check for breaking changes since the last release, would someone mind doing that? I'm also willing to take a PR bumping the version and I'll do a release.

**Comment by andersk** [comment]
@Manishearth Would you be interested in adding me as a collaborator so I can close old resolved issues?

**Comment by Manishearth** [comment]
Yep!

**Comment by Manishearth** [comment]
And yeah let's do a breaking bump.
