### ISSUE TITLE
GC_SWEEPING should be set while GcState is being destructed

### ISSUE THREAD

**Issue by mystor** [Manishearth/rust-gc#16]
When the thread unwinds, and the thread-local state variable is being destroyed, the GC_SWEEPING value isn't set - we should somehow make sure that it is set during that destruction, because otherwise an invalid pointer could be followed during the destruction sequence.

We also need to be sure that no collection can be triggered during the destruction of the thread local storage, because there's no way that would turn out well.

**Comment by DemiMarie** [comment]
Should the various objects with finalizers be freed, once those are implemented?
