### ISSUE TITLE
Recursive objects break

### ISSUE THREAD

**Issue by Elizafox** [Manishearth/rust-gc#168]
Hello,

At present, something like this is impossible, due to a recursive type overflow:

```rust
use gc::{Gc, GcCell, Finalize, Trace};

#[derive(Finalize, Trace)]
struct Node<T: Trace + ?Sized + 'static> {
    prev: Option<Gc<GcCell<Node<T>>>>,
    next: Option<Gc<GcCell<Node<T>>>>,
    data: T,
}
```

A workaround that sacrifices type safety I've found (I would **never** use this in production):

```rust
use std::any::Any;
use gc::{Gc, GcCell, Trace, Finalize};

#[derive(Finalize, Trace)]
struct Node {
    prev: Option<Gc<GcCell<Node>>>,
    next: Option<Gc<GcCell<Node>>>,

    #[unsafe_ignore_trace]
    data: Box<dyn Any>,
}
```

Maybe I'm doing something wrong though. 🤷‍♀️

**Comment by Elizafox** [comment]
I think this might actually be a duplicate of #161, you can close it if it is.

**Comment by andersk** [comment]
This was already fixed in Git by #162, but there hasn’t been a release yet.

**Comment by Elizafox** [comment]
Alright, I'll consider this fixed then. Any chance this can work on stable?

**Comment by andersk** [comment]
Although this was an auxiliary commit on a PR that added a feature requiring Rust nightly, it also happens to make your example work on Rust stable (if that’s what you mean).

**Comment by Elizafox** [comment]
Thank you so much! Yeah, this is perfect.

I'll close for now.
