### ISSUE TITLE
Add `Gc::as_ptr` by analogy with `Rc::as_ptr`

### ISSUE THREAD

**Issue by anna-hope** [Manishearth/rust-gc#172]
For context, I'm working on a bytecode interpreter for the [Lox language](https://craftinginterpreters.com/). In my implementation, I'm currently using `Rc`, but I ultimately would like to use a real GC instead. 

There is a part of my code where I rely on `Rc::as_ptr` to get the raw pointer in order to compare memory addresses, roughly like this:

```rust
if Rc::as_ptr(&x) > Rc::as_ptr(&y) {
    // Do stuff.
}
```

I need this to check which value was older when traversing a linked list. 

I didn't find a similar associated function for `Gc`, and I don't know of another way of accomplishing this without it.

It might also be useful to have for other purposes. 

If we agree that this would be a useful function to have, I would be happy to try implementing it.

**Comment by Manishearth** [comment]
Yeah I'd accept a PR adding this

However, please note that pointer comparison does not guarantee a pointer is "older"

**Comment by andersk** [comment]
> I didn't find a similar associated function for `Gc`, and I don't know of another way of accomplishing this without it.

`Gc::as_ptr` is a fine addition, but for the record, you can [cast any reference to a pointer](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#dereferencing-a-raw-pointer) in safe Rust (`my_gc.as_ref() as *const _` or `&*my_gc as *const _`). One might want to avoid that path in some cases if creating the reference itself would be undefined behavior (if, say, the pointer might be null or misaligned or the wrong type), but that’s not a concern here.

And to second Manishearth’s warning: Rust does not allocate memory in increasing address order, since for example freed memory will be reused.

**Comment by anna-hope** [comment]
@andersk Thanks for pointing that out! I'd forgotten about casting references to pointers. I don't often use `as` in Rust when there are alternatives, but you're right, that would likely work here.

As for the warning on memory address order -- I'll note that. If you're curious, the actual code is [here](https://github.com/anna-hope/rusty-lox/blob/5190202e525a13b7946ae3b21b8c9cdada763eda/rlox_lib/src/vm.rs#L360) and [here](https://github.com/anna-hope/rusty-lox/blob/5190202e525a13b7946ae3b21b8c9cdada763eda/rlox_lib/src/vm.rs#L389). It's a pretty straight port of C code from the book, though it seems C doesn't guarantee memory address order either. Perhaps there is something else to this logic that I'm not understanding, because it works in my implementation (and obviously in the C code from the book) -- unless I'm not using complex enough test cases.

@Manishearth I've submitted a PR with the addition.

**Comment by Manishearth** [comment]
If you're implementing a GC from a book I suspect the book is providing a deliberately naïve implementation.

**Comment by anna-hope** [comment]
> If you're implementing a GC from a book I suspect the book is providing a deliberately naïve implementation.

To clarify, it's the implementation of closing upvalues for closures that uses the pointer comparison. 

The book provides its own implementation of a GC, but I am not attempting that just yet, which is why I wanted to use this crate. Anyway, thanks for merging the PR so quickly!

**Comment by andersk** [comment]
I haven’t tried to read your code, but depending on its implementation details, a [*compacting* garbage collector](https://en.wikipedia.org/wiki/Mark%E2%80%93compact_algorithm) may be able to maintain a guarantee that addresses are ordered chronologically, with the tradeoff that the addresses change during compaction. (This library is not compacting.)
