### ISSUE TITLE
pls add GcCellRef::filter_map like in std::cell::Ref::filter_map

### ISSUE THREAD

**Issue by minus1ms** [Manishearth/rust-gc#176]
pls add GcCellRef::filter_map like in std::cell::Ref::filter_map
i really need it for my project, it can be added quickly i guess, i could fork it too but maybe it will be added fast

**Comment by Manishearth** [comment]
It's not clear to me if this can be done safely? Probably, but it needs some thought.

At the very least if you're in a rush for this please provide a PR.

**Comment by Manishearth** [comment]
Anders put up a PR in https://github.com/Manishearth/rust-gc/pull/177 !

**Comment by minus1ms** [comment]
thx a lot
