### ISSUE TITLE
Pretty printed debug not preserved by passthrough traits

### ISSUE THREAD

**Issue by dtwood** [Manishearth/rust-gc#30]
Printing a Gc<T> with the {:#?} format string doesn't pretty print the string inside (see https://is.gd/OBukfz for a demo, uncommenting the fmt::Debug::fmt(...) gives the correct result

**Comment by dtwood** [comment]
On my phone on a flight, so can't give much more info than that I'm afraid

**Comment by apasel422** [comment]
This seems to have been fixed.

**Comment by mystor** [comment]
This was fixed by #31
