### ISSUE TITLE
`Gc::clone` can be used to access already-destroyed `GcBox`s

### ISSUE THREAD

**Issue by apasel422** [Manishearth/rust-gc#36]
The following code exhibits two invalid reads and two invalid writes to a freed `GcBox`'s root count (via `root_inner` and `unroot_inner`):

```rust
extern crate gc;

use gc::{Gc, GcCell, Trace};

struct Foo(GcCell<Option<Gc<Trace>>>);

unsafe impl Trace for Foo {
    unsafe fn trace(&self) {
        self.0.trace();
    }

    unsafe fn root(&self) {
        self.0.root();
    }

    unsafe fn unroot(&self) {
        self.0.unroot();
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        self.0.borrow().clone();
    }
}

fn main() {
    let a = Gc::new(Foo(GcCell::new(None)));
    let b = Gc::new(1);
    *a.0.borrow_mut() = Some(b);
}
```

This example depends on the order in which `a` and `b` are destroyed.

**Comment by Manishearth** [comment]
Yeah, this is the finalizer problem. Nothing to do with GC::clone, everything to do with drop. Not yet sure which solution to pick -- forbid GC deref / clone during destructors, or run two sweeps where one only calls the drop impl
 and the other deallocates, with a safeguard mark pass in between.

**Comment by apasel422** [comment]
Well, `Deref` checks the sweeping flag, but `Clone` does not.

**Comment by Manishearth** [comment]
Oh, that's a mistake :)

**Comment by apasel422** [comment]
Thoughts on how to proceed?

**Comment by Manishearth** [comment]
Make  clone panic while sweeping?
