### ISSUE TITLE
crates.io lists 0.1.0

### ISSUE THREAD

**Issue by apasel422** [Manishearth/rust-gc#44]
https://crates.io/crates/gc/0.1.0

The version in the repo is now 0.0.9.

**Comment by Manishearth** [comment]
Huh. 0.0.8 wasn't in the repo either, I just assumed one of us forgot to commit the toml changes at some point.

**Comment by mystor** [comment]
Yeah, I noticed that 0.0.8 wasn't in the repo - I guess I messed up and forgot to commit the toml change too :( oops sorry...
