### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by mystor** [Manishearth/rust-gc#46]
We use a bunch of unstable features in rust-gc, most notably our support for custom derive. 

As custom derive is coming to stable "soon":tm:, we should look into how difficult it would be to make a version of the core rust-gc library which doesn't require unstable features, and put the unstable features behind a feature flag.

**Comment by mystor** [comment]
Macros 1.1 is in FCP, so we should figure out our story sometime within the next 3 months as to how to make this work on stable.

**Comment by remexre** [comment]
Macros 1.1 released to stable today!

**Comment by mystor** [comment]
I'll see how much time I can put into this this weekend - it would be pretty nice to have.
