### ISSUE TITLE
Create "slice of Gc<String>" type

### ISSUE THREAD

**Issue by remexre** [Manishearth/rust-gc#60]
I've got a big string, and I want to be able to have lots of references to slices of it. `&str` references don't work with `Gc` (or `Rc` or `Arc`), but it seems like it'd be fairly simple to implement it.

I think this'd just be:

```rust
struct GcStr {
    string: Gc<String>,
    start: usize,
    end: usize,
}
```

That said, I wanted to check here if there was a more efficient way that'd be worth putting in this crate.

Also, it'd make sense to do the same for `CString`/`OsString` (pending #58) and `Vec`.

**Comment by mystor** [comment]
You can implement it more efficiently with some unsafe code. Right now getting the actual `&str` out of the `GcStr` involves 2 pointer derefs (first through `string` and then an offset by `start`, followed by a deref through the inner `String`). 

As the inner String's backing memory will be stable after creating the `Gc<String>` you should be able to store the GcStr as:

```rust
#[derive(Trace, Finalize)]
struct GcStr {
    holder: Gc<String>, // Gc pointer to the GcBox to keep it alive
    #[unsafe_ignore_trace]
    data: *const str, // Actual raw pointer to the underlying string data we're referencing
}
```

It's the same size in memory but takes less derefs to get the data (but also requires `unsafe`). Like `GcLinkedList`, I think this should probably live in a separate crate from `rust-gc`.

**Comment by remexre** [comment]
Okay, sounds good. I'll close this then.
