### ISSUE TITLE
Support for trait objects

### ISSUE THREAD

**Issue by rbartlensky** [Manishearth/rust-gc#72]
Can you wrap a trait object in a `Gc`? I would like to be able to write something like [this](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=36a9cb1379e33a97ba0a21a1b5c93c20). As a workaround, I am currently creating a `Gc<Box<dyn MyTrait>>`, but I don't really like the indirection. I am trying to use `Gc` the way you would use a `Box` or `Rc` with trait objects.

**Comment by Manishearth** [comment]
No, because we don't know how to trace it.

You can write such a thing in a wrapped struct with a custom implementation of `Trace` if you want.

**Comment by rbartlensky** [comment]
Correct me if I am wrong, but even if I create a wrapper, it will still contain some sort of pointer to `MyTrait`. I tried what you suggested, but I am not sure that I got it right.
```rust
pub struct DynWrapper<T: ?Sized + Trace + Finalize> {
    data: T,
}

impl<T: Trace> DynWrapper<T> {
    pub fn new(data: T) -> Self {
        DynWrapper { data  }
    }
}
```

But this doesn't work with trait objects, unless I have a `*/&/Box/Rc T` instead of a plain `T`. I am trying to avoid the extra heap allocation, because `Gc` already does one.

**Comment by Manishearth** [comment]
No, you have to do this on a per-trait-object basis

```rust
pub struct MyTraitWrapper {
   inner: Box<Trait>
}
```

and your `Trait` needs to inherit from `Trace` (you can't do `Box<Trait+Trace>` sadly). You can also create a new trait that inherits from both traits.

If you want to avoid the heap allocation you can do the following:

```rust
pub struct MyTraitWrapper {
  inner: Trait
```

which is also a dynamically sized type and can be directly placed inside `Gc`. It's tricker to construct though, you'll likely need a constructor that directly returns `Gc<MyTraitWrapper>`

**Comment by rbartlensky** [comment]
Thank you for your help. I think I will stick with your first suggestion.

**Comment by andersk** [comment]
The original code actually just works in nightly Rust with the `nightly` crate feature, due to `CoerceUnsized` (67cc6e2d4d421b83b9e7b41effdf42f020e9ac2b).

**Comment by andersk** [comment]
With the `nightly` crate feature, #160 adds a conversion from `Box<dyn Trait>` to `Gc<dyn Trait>`. So I think trait objects are now supported as well as they can be.

The tracking issue for the required unstable Rust feature is

- rust-lang/rust#18598
