### ISSUE TITLE
Ref counts and deterministic cleanup

### ISSUE THREAD

**Issue by andrewchambers** [Manishearth/rust-gc#73]
Have you considered using reference counts for early predictable cleanup, but then also the GC for cycle detection? I think that is similar to what python does under the hood.

That might make gc'd code behave more like normal rust, which may be desirable. Feel free to close this, I was just wondering if anyone has any thoughts on that.

**Comment by Manishearth** [comment]
We already use reference counts for root detection.

The space of GC designs is restricted if you want the API to work from safe rust. Python can do a lot of things because it has control of it's runtime
