### ISSUE TITLE
Can't double-unroot a Gc<T>

### ISSUE THREAD

**Issue by AljoschaMeyer** [Manishearth/rust-gc#74]
I got [some code](https://github.com/AljoschaMeyer/pavo-bootstrap/blob/master/src/value.rs#L28) using this crate that panics with ["Can't double-unroot a Gc<T>"](https://github.com/Manishearth/rust-gc/blob/master/gc/src/lib.rs#L217). Debugging this will be a lot of work (it's an interpreter for a language and only some input programs trigger this), so I'd like to ask first: Is that assertion supposed to be an invariant (i.e. the crash is a bug in the Gc crate), or does it protect against incorrect usage (i.e. my calling code is violating some contract)?

**Comment by Manishearth** [comment]
I mean, it's an invariant, but it's one you're supposed to uphold, so it's a bug in the usage

**Comment by AljoschaMeyer** [comment]
From the docs, I can't find out which contract I might have violated. It says "This can be used pretty much like `Rc`, with the exception of interior mutability.", but doesn't go into details about what those exceptions are. The [blog post](https://manishearth.github.io/blog/2015/09/01/designing-a-gc-in-rust/) doesn't mention any restrictions in the usage of `GcCell`s either. Overall this gives the impression that there really is no possible buggy usage.

Does that imply that there must be something wrong with a `Trace` implementation? Does the crate guarantee that this sort of panic can *only* happen through unsafety (`#[unsafe_empty_trace]` in particular)?

**Comment by AljoschaMeyer** [comment]
Or is there a blunder with custom trace implementations like e.g. the one [below](https://github.com/AljoschaMeyer/pavo-bootstrap/blob/master/src/gc_foreign.rs#L28) (a wrapper around [im-rs::Vector](https://docs.rs/im/13.0.0/im/vector/enum.Vector.html)):

```rust
/// A garbage-collectable `im_rc::Vector`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Vector<T: Clone>(pub im_rc::Vector<T>);

impl<T: Trace + Clone> Finalize for Vector<T> {}
unsafe impl<T: Trace + Clone> Trace for Vector<T> {
    custom_trace!(this, {
        for e in this.0.iter() {
            mark(e);
        }
    });
}
```

**Comment by Manishearth** [comment]
Yes, it's a blunder in a custom trace impl. You can't trigger this otherwise.
