### ISSUE TITLE
Finalize and Trace on more arrays

### ISSUE THREAD

**Issue by AljoschaMeyer** [Manishearth/rust-gc#75]
Hi, it would be really neat if some more arrays sizes than just the numbers 0 to 31 implemented Trace and Finalize. Would you be open to adding the next few powers of two as well?

(I actually only need `[T; 32]`, having to wrap these in a newtype when the crate supports arrays up to 31 is oddly frustrating. And `[T; 32]`, `[T; 64]` etc are probably more common than, say, `[T; 29]`.)

**Comment by Manishearth** [comment]
I'm okay with going up to 256.
