### ISSUE TITLE
Provide GcCellRef::map

### ISSUE THREAD

**Issue by xfix** [Manishearth/rust-gc#78]
Similar to `std::cell::Ref::map`.

**Comment by HalidOdat** [comment]
@Manishearth would it be possible to publish a new version to crates.io , so we can use the `map` functions :)

**Comment by Manishearth** [comment]
Can you make a PR with version bumps? Typically that's when I make releases

**Comment by HalidOdat** [comment]
> Can you make a PR with version bumps? Typically that's when I make releases

Sure :)

**Comment by HalidOdat** [comment]
@Manishearth here is the version bump PR #105 

About the version, I have a question why is the version on master 1.3.4 but on crates.io it is 0.3.5, I made the version 0.3.6 is this right?

**Comment by Manishearth** [comment]
Looks like I forgot to push :smile:
