### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by Razican** [Manishearth/rust-gc#92]
There have been multiple updates in this repository, and it would be nice to have them in crates.io.

**Comment by Razican** [comment]
Hi @Manishearth I think it was not released yet in crates.io

**Comment by Manishearth** [comment]
Yeah, I can't publish the derive crate, only @mystor can right now

**Comment by Manishearth** [comment]
Done

**Comment by Razican** [comment]
Thank you so much!
