### ISSUE TITLE
Display for Ref types

### ISSUE THREAD

**Issue by ilarioc** [Manishearth/rust-gc#99]
Hi!
I was wondering if there is any reason why Display is not implemented for `GcCellRef<T>` and `GcCellRefMut<T>` if `T: Display`?

**Comment by Manishearth** [comment]
No reason, PRs welcome

**Comment by Manishearth** [comment]
You should be able to just dereference and Display though

**Comment by ilarioc** [comment]
I hadn't thought about deref and went on and implemented it #100
